### PR TITLE
Fix #64 jvm options with spaces

### LINKED ISSUE #64: clojure.sh script breaks for some jvm options
If we have a deps.edn file like this : 

```clojure
{:deps {}
 :aliases
 {:dev
  {:jvm-opts ["-Dflowstorm.jarEditorCommand=emacsclient <<FILE>>"]}}}
```

then running on that folder the enrich initialization command:

```
/home/jmonetta/.emacs.d/elpa/cider-20240423.1541/clojure.sh /usr/local/bin/clojure -Sdeps \{\:deps\ \{nrepl/nrepl\ \{\:mvn/version\ \"1.1.1\"\}\ cider/cider-nrepl\ \{\:mvn/version\ \"0.47.0\"\}\ refactor-nrepl/refactor-nrepl\ \{\:mvn/version\ \"3.10.0\"\}\}\ \:aliases\ \{\:cider/nrepl\ \{\:main-opts\ \[\"-m\"\ \"nrepl.cmdline\"\ \"--middleware\"\ \"\[refactor-nrepl.middleware/wrap-refactor\,cider.nrepl/cider-middleware\]\"\]\}\}\} -M:cider/nrepl:dev
```

breaks with error : 

```
/home/jmonetta/.emacs.d/elpa/cider-20240423.1541/clojure.sh: line 48: warning: here-document at line 48 delimited by end-of-file (wanted `FILE')
```

It looks like the `eval "$cmd"` breaks when a substring like `<<FILE>>` gets into it.

### PR DESCRIPTION
**Pull request by jpmonettas**
> Fixes https://github.com/clojure-emacs/enrich-classpath/issues/64

### CODE REVIEW

**Comment by vemv** [comment]
Thanks!

Tests pass.

Did you have the chance to verify that things will actually work? I'd be afraid of clojure.sh choking with `<<FILE>>`

(although you said it doesn't appear to - can trust)

**Comment by jpmonettas** [comment]
> Thanks!
> 
> Tests pass.
> 
> Did you have the chance to verify that things will actually work? I'd be afraid of clojure.sh choking with `<<FILE>>`
> 
> (although you said it doesn't appear to - can trust)

yes, I'm currently using that snapshot and works fine.

**Comment by vemv** [comment]
Thanks - release later today

**Comment by vemv** [comment]
jars are out and https://github.com/clojure-emacs/cider/commit/1cd6ab7b7cb4a7e079a273600c4d28307c3aba40 has landed

(a Melpa unstable release gets generated a couple hours later)

**Pull request merged**
